/-
# Part IX.6  Chain dynamics: the Rouse spectrum and the cost of equilibrating a chain

Part VIII priced sampling in units of the relaxation time of the slowest process, but left
that time as a free parameter.  For a polymer it is not free: connectivity alone fixes it.
This file solves the standard model of chain dynamics -- the Rouse model, a chain of beads
coupled by harmonic springs and dragged by the solvent, with free ends -- and feeds the
answer back into the sampling bound.

The dynamics is generated by the discrete Laplacian of the chain with free-end (Neumann)
boundary conditions.  Working with the mode function `rouseMode` `v(s) = cos(θ(s + 1/2))`,
`θ = pπ/N`:

* `rouseMode_eigen` -- `2v(s) - v(s-1) - v(s+1) = λ_p·v(s)` for every `s`, with
  `λ_p = 4 sin²(pπ/2N)`: the Rouse modes diagonalise the chain Laplacian, exactly.
* `rouseMode_boundary_left`, `rouseMode_boundary_right` -- and they satisfy the free-end
  conditions `v(-1) = v(0)`, `v(N) = v(N-1)`, so they are the modes of the *chain*, not of a
  ring or of a clamped chain.
* `rouse_slowest_eigenvalue_le` -- the slowest mode has `λ₁ ≤ π²/N²`, hence a relaxation time
  `τ₁ ≥ N²/π²`: the Rouse `τ ~ N²` law.
* `rouse_run_length` -- combined with the sampling bound of Part VIII: a simulation of a chain
  of `N` monomers that starts a distance `d` from equilibrium and reports populations to
  accuracy `eps` must run for at least `(1 - eps/d)·N²/π²` steps.  The cost of an ensemble of
  a disordered region therefore grows at least quadratically with its length *before* any
  barrier is taken into account, and `Relax.barrier_cost` multiplies that by `exp B`.

This is the dynamical counterpart of the capacity law of Part III: the ensemble one must
represent needs exponentially many structures, and the trajectory one must run to observe it
needs quadratically many steps per length.
-/
import Mathlib
import RequestProject.Relaxation

namespace IDR

namespace Rouse

/-- The Rouse mode of index `p` on a chain of `N` beads, as a function of the (real) bead
coordinate: `v(s) = cos(pπ(s + 1/2)/N)`. -/
noncomputable def rouseMode (N : ℕ) (p : ℕ) (s : ℝ) : ℝ :=
  Real.cos ((p : ℝ) * Real.pi / N * (s + 1 / 2))

/-- The Rouse eigenvalue: `λ_p = 4 sin²(pπ/2N) = 2 - 2cos(pπ/N)`. -/
noncomputable def rouseEigen (N : ℕ) (p : ℕ) : ℝ :=
  4 * Real.sin ((p : ℝ) * Real.pi / (2 * N)) ^ 2

lemma rouseEigen_eq (N p : ℕ) (hN : 0 < N) :
    rouseEigen N p = 2 - 2 * Real.cos ((p : ℝ) * Real.pi / N) := by
  have hN' : (N : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr hN.ne'
  unfold rouseEigen
  have hhalf : (p : ℝ) * Real.pi / N = 2 * ((p : ℝ) * Real.pi / (2 * N)) := by
    field_simp
  have key : ∀ x : ℝ, 2 - 2 * Real.cos (2 * x) = 4 * Real.sin x ^ 2 := by
    intro x
    rw [Real.cos_two_mul']
    nlinarith [Real.sin_sq_add_cos_sq x]
  rw [hhalf, key]

/-- **The Rouse modes diagonalise the chain Laplacian.**  Exactly, at every point. -/
theorem rouseMode_eigen (N p : ℕ) (hN : 0 < N) (s : ℝ) :
    2 * rouseMode N p s - rouseMode N p (s - 1) - rouseMode N p (s + 1)
      = rouseEigen N p * rouseMode N p s := by
  set th : ℝ := (p : ℝ) * Real.pi / N with hth
  unfold rouseMode
  rw [rouseEigen_eq N p hN, ← hth]
  have h1 : th * (s - 1 + 1 / 2) = th * (s + 1 / 2) - th := by ring
  have h2 : th * (s + 1 + 1 / 2) = th * (s + 1 / 2) + th := by ring
  rw [h1, h2, Real.cos_sub, Real.cos_add]
  ring

/-- Free-end (Neumann) boundary condition at the first bead. -/
theorem rouseMode_boundary_left (N p : ℕ) : rouseMode N p (-1) = rouseMode N p 0 := by
  unfold rouseMode
  have h : (p : ℝ) * Real.pi / N * (-1 + 1 / 2)
      = -((p : ℝ) * Real.pi / N * (0 + 1 / 2)) := by ring
  rw [h, Real.cos_neg]

/-- Free-end (Neumann) boundary condition at the last bead. -/
theorem rouseMode_boundary_right (N p : ℕ) (hN : 0 < N) :
    rouseMode N p (N : ℝ) = rouseMode N p ((N : ℝ) - 1) := by
  have hN' : (N : ℝ) ≠ 0 := Nat.cast_ne_zero.mpr hN.ne'
  set th : ℝ := (p : ℝ) * Real.pi / N with hth
  have hthN : th * (N : ℝ) = (p : ℝ) * Real.pi := by
    rw [hth]; field_simp
  unfold rouseMode
  rw [← hth]
  have e1 : th * ((N : ℝ) + 1 / 2) = (p : ℝ) * Real.pi + th * (1 / 2) := by
    rw [← hthN]; ring
  have e2 : th * ((N : ℝ) - 1 + 1 / 2) = (p : ℝ) * Real.pi - th * (1 / 2) := by
    rw [← hthN]; ring
  rw [e1, e2, Real.cos_add, Real.cos_sub, Real.sin_nat_mul_pi]
  ring

/-- **The Rouse `τ ~ N²` law.**  The slowest relaxing mode has eigenvalue at most `π²/N²`, so
its relaxation time is at least `N²/π²`. -/
theorem rouse_slowest_eigenvalue_le {N : ℕ} (hN : 0 < N) :
    rouseEigen N 1 ≤ Real.pi ^ 2 / (N : ℝ) ^ 2 := by
  have hN' : (0 : ℝ) < N := by exact_mod_cast hN
  have hx : 0 ≤ Real.pi / (2 * N) := by positivity
  have hsin : Real.sin (Real.pi / (2 * N)) ≤ Real.pi / (2 * N) := Real.sin_le hx
  have hsin0 : 0 ≤ Real.sin (Real.pi / (2 * N)) := by
    refine Real.sin_nonneg_of_nonneg_of_le_pi hx ?_
    rw [div_le_iff₀ (by positivity)]
    have h1 : (1 : ℝ) ≤ (N : ℝ) := by exact_mod_cast hN
    nlinarith [Real.pi_pos, h1]
  have hsq : Real.sin (Real.pi / (2 * N)) ^ 2 ≤ (Real.pi / (2 * N)) ^ 2 :=
    pow_le_pow_left₀ hsin0 hsin 2
  unfold rouseEigen
  have : (4 : ℝ) * (Real.pi / (2 * N)) ^ 2 = Real.pi ^ 2 / (N : ℝ) ^ 2 := by
    field_simp
    ring
  calc 4 * Real.sin ((1 : ℕ) * Real.pi / (2 * N)) ^ 2
      = 4 * Real.sin (Real.pi / (2 * N)) ^ 2 := by norm_num
    _ ≤ 4 * (Real.pi / (2 * N)) ^ 2 := by linarith
    _ = Real.pi ^ 2 / (N : ℝ) ^ 2 := this

/-- **The cost of equilibrating a chain grows at least quadratically with its length.**
A run of `t` steps whose slowest mode contracts by `1 - λ₁` per step, started a distance `d`
from equilibrium and reporting the populations to accuracy `eps`, must satisfy
`(1 - eps/d)·N²/π² ≤ t`. -/
theorem rouse_run_length {N : ℕ} (hN : 0 < N) {d eps : ℝ} (hd : 0 < d)
    (hlam : 0 ≤ 1 - rouseEigen N 1) (t : ℕ)
    (hrun : (1 - rouseEigen N 1) ^ t * d ≤ eps) :
    (1 - eps / d) * (N : ℝ) ^ 2 / Real.pi ^ 2 ≤ t := by
  have hN' : (0 : ℝ) < N := by exact_mod_cast hN
  have hpi : 0 < Real.pi := Real.pi_pos
  have hbase := Relax.relaxation_lower_bound hlam hd t hrun
  have hstep : (1 : ℝ) - (1 - rouseEigen N 1) = rouseEigen N 1 := by ring
  rw [hstep] at hbase
  have hle : (t : ℝ) * rouseEigen N 1 ≤ (t : ℝ) * (Real.pi ^ 2 / (N : ℝ) ^ 2) :=
    mul_le_mul_of_nonneg_left (rouse_slowest_eigenvalue_le hN) (Nat.cast_nonneg t)
  have hcomb : 1 - eps / d ≤ (t : ℝ) * (Real.pi ^ 2 / (N : ℝ) ^ 2) := le_trans hbase hle
  have hNsq : (0 : ℝ) < (N : ℝ) ^ 2 := by positivity
  have h2 := mul_le_mul_of_nonneg_right hcomb hNsq.le
  have h3 : (t : ℝ) * (Real.pi ^ 2 / (N : ℝ) ^ 2) * (N : ℝ) ^ 2 = (t : ℝ) * Real.pi ^ 2 := by
    field_simp
  rw [h3] at h2
  rw [div_le_iff₀ (by positivity : (0 : ℝ) < Real.pi ^ 2)]
  exact h2

end Rouse

end IDR
